name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish to PyPI
      uses: JRubics/poetry-publish@v1.5
      with:
        python_version: "3.8"
        build_format: "sdist"
        pypi_token: ${{ secrets.PYPI_TOKEN }}