name: publish autograde version autograde

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Publish Python Package
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry build --format sdist
        poetry publish